var tree_node=new Array(0,"1","","","","",4,"","","",-1,0,"1.1","","","","",3,"","","",-1,2,"1.1.1","","","",3,"","http://fafjljk","",2,"1.1.2","","","",3,"","","",1,0,"1.2","","","","",3,"","","",-1,2,"1.2.1","","","",3,"","","",2,"1.2.2","","","",3,"","","",1,1,0,"2","","","","",4,"","","",-1,2,"2.1","","","",3,"","","",1,2,"3","","","",4,"","","",2,"4","","","",4,"","","",2,"5","","","",4,"","","",5);
document.write('<style>');
document.write('TD.Tree_FOLDER_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FOLDER_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_1{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_2{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('TD.Tree_FILE_3{height:0pt;padding:0pt 5pt 0pt 2pt;}');
document.write('</style>');
var tree=new Tree_treeView();
tree.useImage=true;
tree.useTitleAsHint=true;
tree.useTitleAsStatus=true;
tree.useHint=true;
tree.useStatus=true;
tree.showSelect=true;
tree.showLine=false;
tree.Indent=13;
tree.folderImg1="";
tree.lineFolder="./";
tree.folderImg2="";
tree.fileImg="";
tree.target="_blank";
tree.folderClass1="Tree_FOLDER_1";
tree.folderClass2="Tree_FOLDER_2";
tree.folderClass3="Tree_FOLDER_3";
tree.fileClass1="Tree_FILE_1";
tree.fileClass2="Tree_FILE_2";
tree.fileClass3="Tree_FILE_3";
Tree_buildTree(tree_node,tree);
